name: Alarm
options:
  bundleIdPrefix: com.yumingxie
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.0"
    ENABLE_STRICT_CONCURRENCY: minimal
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_LANGUAGE: en

targets:
  Alarm:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: .
        excludes:
          - project.yml
          - "*.xcodeproj/**"
          - "*.xcworkspace/**"
          - memory/**
          - UITests/**
          - AlarmWidget/**
      - path: Shared
    resources:
      - path: Assets.xcassets
      - path: Localizable.xcstrings
      - path: Sounds
    info:
      path: Info.plist
      properties:
        CFBundleDevelopmentRegion: "$(DEVELOPMENT_LANGUAGE)"
        CFBundleDisplayName: Alarm
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        CFBundleIdentifier: "$(PRODUCT_BUNDLE_IDENTIFIER)"
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: "$(PRODUCT_NAME)"
        CFBundlePackageType: "$(PRODUCT_BUNDLE_PACKAGE_TYPE)"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        CFBundleLocalizations:
          - en
          - zh-Hans
        UIBackgroundModes:
          - audio
        NSSupportsLiveActivities: true
        NSSupportsLiveActivitiesFrequentUpdates: true
        NSAlarmKitUsageDescription: "Alarm uses AlarmKit to ring alarms reliably even when the app is not running."
        NSLocationWhenInUseUsageDescription: "Alarm uses your location to calculate real-time commute duration and remind you to leave on time."
        NSCalendarsFullAccessUsageDescription: "Alarm reads your calendar to auto-create alarms before events."
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities:
          - arm64
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: Alarm.com
        INFOPLIST_FILE: Info.plist
        DEVELOPMENT_TEAM: HKK65P5735
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: Alarm/Alarm.entitlements
    dependencies:
      - sdk: SwiftData.framework
      - sdk: MapKit.framework
      - sdk: CoreLocation.framework
      - sdk: UserNotifications.framework
      - sdk: AlarmKit.framework
      - sdk: AppIntents.framework
      - sdk: ActivityKit.framework
      - sdk: EventKit.framework
      - sdk: WidgetKit.framework
      - target: AlarmWidget
        embed: true

  AlarmWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: AlarmWidget
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: Alarm.com.AlarmWidget
        DEVELOPMENT_TEAM: HKK65P5735
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: AlarmWidget/AlarmWidget.entitlements
    dependencies:
      - sdk: WidgetKit.framework
      - sdk: SwiftUI.framework
    info:
      path: AlarmWidget/Info.plist
      properties:
        CFBundleDisplayName: "Alarm Widget"
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        CFBundleIdentifier: "$(PRODUCT_BUNDLE_IDENTIFIER)"
        CFBundleName: "$(PRODUCT_NAME)"
        CFBundlePackageType: XPC!
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension

  AlarmUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: UITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: Alarm.com.AlarmUITests
        TEST_TARGET_NAME: Alarm
        GENERATE_INFOPLIST_FILE: YES
        FRAMEWORK_SEARCH_PATHS: "$(DEVELOPER_FRAMEWORKS_DIR) $(PLATFORM_DIR)/Developer/Library/Frameworks $(inherited)"
    dependencies:
      - target: Alarm

schemes:
  Alarm:
    build:
      targets:
        Alarm: all
        AlarmWidget: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - name: AlarmUITests
          parallelizable: false
